### ISSUE TITLE
写了个超快的转换工具，最新版参考了您这个的一部份内容

### ISSUE THREAD

**Issue by magicbear** [jmkl009/PalworldCharacterTransfer#5]
写了个超快的转换工具，最新版参考了您这个的一部份内容，补了个连接到Thanks上去 :-)
https://github.com/magicbear/palworld-server-toolkit

欢迎提Issues

**Comment by jmkl009** [comment]
这个从gvas直接读取的方法确实很快。如果可以的话我也能参考你的读取方式写一个吗？我也会补一个thanks上去。也不可能和你的工具竞争，只是我自己对优化和速度有很高的要求。

**Comment by magicbear** [comment]
> 哈哈我要是不重复造一个轮子，我怎么能完全理解它。我感觉还有优化空间，所以想试试。之前没花多少心思在这个脚本上，我还比较遗憾。

你这个脚本优化空间可太大了

**Comment by jmkl009** [comment]
我是说你的gvas读取依旧还有优化空间

**Comment by magicbear** [comment]
> 我是说你的gvas读取依旧还有优化空间

要不要加个QQ聊～ 342641
