### ISSUE TITLE
Guild issue

### ISSUE THREAD

**Issue by uythoang** [jmkl009/PalworldCharacterTransfer#6]
I was able to use this to transfer my character from one dedicated server to another. However, in the new server I am no longer associated with my guild so I do not have access to my base.

**Comment by jmkl009** [comment]
Right, please use other script for your specific purpose. This script is meant to transfer character only and is not compatible with the way you have transferred your base. I apologize, but the main purpose of the script is to cause minmal effect to the existing new world. As a result, the transferred character takes on the guild ID of the new character to account for the case where the new character already joined a guild. This new guild ID is different from the guild your base belongs to and thus you can no longer access your base. To transfer both your base and character, please use other scripts available.

**Comment by uythoang** [comment]
Ah okay. Could you suggest any scripts that might work for my purposes? Thanks.

**Comment by uythoang** [comment]
@BrotherCal That worked perfectly, thanks!
