### ISSUE TITLE
我有一个新方法，不需要使用python转换存档文件，而且可以将文件放回单人游戏使用

### ISSUE THREAD

**Issue by number201724** [jmkl009/PalworldCharacterTransfer#7]
我有一个新方法，不需要使用python转换存档文件，而且可以将文件放回单人游戏使用
通过给服务器打patch，让服务器正确识别其他玩家的steamid的hash和通过指定单人模式的steamid来让dedicated server也能使用本地用户的.sav文件

https://github.com/number201724/PalServerHostFix

**Comment by jmkl009** [comment]
你这个方法能让服务器的存档转回单机使用吗？

**Comment by number201724** [comment]
可以是可以，但是有条件，比如A用户创建的存档，可以让A用户放回单机用，如果B用户放回来有点问题

**Comment by jmkl009** [comment]
还有一个问题，如果帕鲁的信息保留在本地的Level.sav里，如果服务器已经有一些人在玩有自己的存档的话，那我们只能把人物文件复制到服务器，这样的话是不是不能保留在本地玩的时候抓的帕鲁了？

**Comment by number201724** [comment]
不要这样搞，会出错，不如用magicbear的工具把数据转进去，我做这个的目的主要是方便单机存档放到专用服务器上跑
